### PR TITLE
migration to new container based travis

### PR DESCRIPTION
**Pull request by edoput**
must wait until libsecret-1-dev get approved in https://github.com/travis-ci/apt-package-whitelist/issues/350

### CODE REVIEW

**Comment by nicokoch** [comment]
Wow you're fast. Would you mind resolving the very unfortunate merge conflicts?

I will wait for libsecret-1-dev approval before merge. Thanks once again for your contributions!

**Comment by edoput** [comment]
just to keep you in the loop, the package libsecret-1-dev has been added to the whitelist, can you run the build and see what pops out?

**Comment by nicokoch** [comment]
I ran the travis build and it failed. you can find the build output [here](https://travis-ci.org/nicokoch/secret-rs/jobs/72440132).
`E: Unable to locate package libsecret-1-dev` seems to be the problem. Maybe the whitelist isnt updated on production yet?

**Comment by edoput** [comment]
I found that on precise, the current ubuntu version for the container, the package libsecret [is not published](https://launchpad.net/ubuntu/precise/+source/libsecret) we must wait until travis-ci/travis-ci#2046 get closed, then we can merge.

If you want to speed up things we can always try to build from sources

**Comment by nicokoch** [comment]
Building from source is something I would want to have embedded in the secret-sys crate, similar to [git2-rs](https://github.com/alexcrichton/git2-rs/blob/master/libgit2-sys/build.rs). This is considered good rust etiquette according to alexcrichton.

But doing so is also very error-prone and I'm not sure if any licensing issues arise if we include libsecret as a git submodule.

**Pull request closed without merging**
